[project]
name = "Cinema-Bot"
version = "0.1.0"
description = "This is my Personal File Rename and Forward bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.3",
]
